# Generated by Django 3.2.13 on 2022-06-05 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0003_auto_20220604_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='image',
            old_name='comment',
            new_name='comments',
        ),
        migrations.AddField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='instagramapp.profile'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='images/66.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(default='images/67.jpg', null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
