# Generated by Django 3.2.13 on 2022-06-05 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0004_auto_20220605_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(default='True', on_delete=django.db.models.deletion.CASCADE, to='instagramapp.profile'),
        ),
    ]
