# Generated by Django 3.2.13 on 2022-06-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0005_alter_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
