# Generated by Django 3.2.13 on 2022-06-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0006_alter_profile_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='comments',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(default='images/67.jpg', null=True, upload_to='images/'),
        ),
    ]
